<<<<<<< HEAD
# fly.toml app configuration file generated for too-many-coins-api on 2026-02-10T00:24:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
=======
app = "too-many-coins-api"
>>>>>>> a7f569c (Refactor authentication flow and database schema for Phase 0)

app = 'too-many-coins-api'
primary_region = 'iad'

[build]

<<<<<<< HEAD
[http_service]
=======


[[services]]
>>>>>>> a7f569c (Refactor authentication flow and database schema for Phase 0)
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
